FROM ubuntu:latest
MAINTAINER froskekongen <erlend.aune.1983@gmail.com>

# Necessary to add a ppa
RUN apt-get update && apt-get install -y python3-pip
RUN pip3 install tweepy
RUN pip3 install pymongo
